DROP TABLE IF EXISTS BOARD;

CREATE TABLE BOARD
(
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(250) NOT NULL,
    fistname VARCHAR(250) DEFAULT NULL,
    lastname VARCHAR(250) DEFAULT NULL
);